### ISSUE TITLE
Combine keyword and image search

### ISSUE THREAD

**Issue by nsanden** [nsanden/copycatcher#3]
Let's make the following changes:
1) Remove image url box
2) Combine keyword and upload image boxes so both are required

This way, the user thinks he must upload image and write in the text from the image (that both are required before it will work correctly). Also, it gives us a free translation. The user is translating his own shirt.

Finally, it allows your script to only use the keywords the user typed in to do the searching and not relying on the OCR code.

**Comment by jmpueblo** [comment]
@nsanden 

Done. Please run "composer update".
Shall I create a database to store uploaded images and keyword pairs?

**Comment by nsanden** [comment]
Yes please do

**Comment by nsanden** [comment]
created a new issue for this at #5
