### ISSUE TITLE
Change masonry to a list view and add match "score"

### ISSUE THREAD

**Issue by nsanden** [nsanden/copycatcher#4]
I added `title` and match percentage `score` fields to the json output so each search result has a score now. Let's sort by that and also list it in our list view.

The score is always 65 right now but i'll build the real logic for that soon.

For example:

[shirt image]    [title_linked_to_shirt]    [score]
[shirt image]    [title_linked_to_shirt]    [score]
[shirt image]    [title_linked_to_shirt]    [score]

**Comment by jmpueblo** [comment]
@nsanden 

Done. Please run "composer update".
